apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-i1jh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/fduthill-tenant/another-build-custom/devfile-sample-code-with-quarkus-i1jh@sha256:5160174a6736310cee6048cb29c2e69a281fda66ea92d5b3bc0a5c5dcdd72162
        name: my-java-quarkus
        resources: {}
status: {}
